server:
  port: 11000
spring:
  application:
    name: ware
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.5.5:3306/newhopemail_wms?serverTimezone=GMT%2B8
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.5:8848
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto